Swati nearest branch
TechnocultureResearch/landlog pull request #15
Opened 2023-02-05 10:56 UTC by GitCodeSM

- changed nearest.py for the get the nearest bus stops function
- changed UtilityLocation.BUS_STOP string "bus stop" to "bus depot" for accuracy
- removed launch.json

2023-02-08 16:33 UTC, closed without merging

2023-02-10 16:52 UTC, sutyum requested changes
Lots of issues, i have provided detailed comments

2023-02-10 16:52 UTC, sutyum commented on locesh/distanceto/main.py
> +def mapmyindia_access_tokens(client_id: str, client_secret: str) -> tuple[str, str]:
`Tuple` not `tuple`. It needs to be imported from typing

2023-02-10 16:52 UTC, sutyum commented on locesh/distanceto/nearest.py
> +    loc_str = str(lat) + "," + str(lon)
use type annotations

2023-02-10 16:52 UTC, sutyum commented on locesh/distanceto/nearest.py
> +    places_json_obj = requests.get(api_loc_url, token_dict).json()
use pydantic, use type annotation

2023-02-10 16:52 UTC, sutyum commented on locesh/distanceto/nearest.py
> +    try:
completely unnecessary, use pydantic

2023-02-10 16:52 UTC, sutyum commented on locesh/distanceto/nearest.py
> +                    "place_distance": x["distance"],
you should never do a keyword lookup on API respones. Use pydantic correctly

2023-02-10 16:52 UTC, sutyum commented on locesh/distanceto/nearest.py
> +    except:
except what? `except:` as well as `except Exception:` are poor coding practice. Always be explicit about the exceptions you are trying to catch. In this case it should have been `except KeyError as e:`

2023-02-10 16:52 UTC, sutyum commented on locesh/distanceto/nearest.py
> +        print("Exception: Key error. key 'suggestedLocations' not found.")
catching an exception just to print something is almost never useful

2023-02-10 16:52 UTC, sutyum commented on locesh/distanceto/types.py
> +'''
docstring not useful or informative

2023-02-10 16:52 UTC, sutyum commented on locesh/distanceto/types.py
> +    BUS_STOP = "bus stop"
ideally enum string should not contain a space character. prefer "bus_stop"

2023-02-10 16:52 UTC, sutyum commented on locesh/distanceto/types.py
> +    keywords: list[str] = []
`keywords: list[str] = []` bad practice, use `keywords: list[str] = Field(default_factory=list)` instead

2023-02-10 16:52 UTC, sutyum commented on locesh/distanceto/types.py
> +    order_index: str
why is this a string?

2023-02-10 16:52 UTC, sutyum commented on locesh/distanceto/types.py
> +
missing pydantic model to parse the entire response with list of n UtilDistances

2023-02-10 16:52 UTC, sutyum commented on locesh/server/api.py
> +) -> tuple[str, str]:
event triggers should return `None`

2023-02-10 16:52 UTC, sutyum commented on locesh/server/api.py
> +    client_id: str = client_id, client_secret: str = client_secret
event triggers should not require any inputs. These two values should come from the env variables

2023-02-10 16:52 UTC, sutyum commented on locesh/server/api.py
> +    return token_type, access_token
should not be returning anything

2023-02-10 16:52 UTC, sutyum commented on locesh/server/api.py
> +    token_type, access_token = mapmyindia_access_tokens(client_id, client_secret)
you should have a seperate file with these two variables (eg: map_my_india.py), and these values should be imported here from that file. 

```py
# map_my_india.py
TOKEN_TYPE: str = ""
ACCESS_TOKEN: str = ""
```

then set values to these variables in the startup event trigger. During any api calls to mapmyindia api, use these values by importing these variables from map_my_india.py file

2023-02-10 16:52 UTC, sutyum commented on locesh/server/api.py
> +    token_type: str = token_type,
not needed, also not correct

2023-02-10 16:52 UTC, sutyum commented on locesh/server/api.py
> +token_type, access_token = startup_event(client_id, client_secret)
you are not supposed to call this function, fastapi calls it internally when the server starts

2023-02-10 16:52 UTC, sutyum commented on locesh/server/api.py
>      print(distances)
comment out prints

2023-02-11 10:47 UTC, GitCodeSM commented on locesh/distanceto/nearest.py
> +    token_dict: Dict = {
changed to 
token_dict: Dict[str, str]

2023-02-11 11:00 UTC, GitCodeSM commented on locesh/distanceto/nearest.py
> +        + keywords
keywords changed to a list of strings transformed as a string
keywords: str = ",".join(utility)

2023-02-11 11:01 UTC, GitCodeSM commented on locesh/distanceto/nearest.py
> +    token_type, access_token, lat, lon, keywords
types provided in fetch_nearest... function

2023-02-11 11:08 UTC, GitCodeSM commented on locesh/distanceto/nearest.py
> +    except:
changed to KeyError as e

2023-02-11 11:11 UTC, GitCodeSM commented on locesh/distanceto/nearest.py
> +        print("Exception: Key error. key 'suggestedLocations' not found.")
changed

2023-02-11 11:17 UTC, GitCodeSM commented on locesh/distanceto/types.py
> +'''
changed

2023-02-11 11:23 UTC, GitCodeSM commented on locesh/distanceto/types.py
> +    keywords: list[str] = []
Can't change: Shows error:
Incompatible types in assignment (expression has type "Field[List[_T]]", variable has type "List[str]")  [assignment]mypy(error)

2023-02-11 11:24 UTC, GitCodeSM commented on locesh/distanceto/types.py
> +    order_index: str
all results of api are strings

2023-02-11 11:25 UTC, GitCodeSM commented on locesh/server/api.py
> +) -> tuple[str, str]:
ok. changed to none

2023-02-11 11:32 UTC, GitCodeSM commented on locesh/server/api.py
> +    client_id: str = client_id, client_secret: str = client_secret
changed the startup event

2023-02-11 11:33 UTC, GitCodeSM commented on locesh/server/api.py
> +    return token_type, access_token
ok. removed returns

2023-02-11 11:35 UTC, GitCodeSM commented on locesh/server/api.py
> +    token_type, access_token = mapmyindia_access_tokens(client_id, client_secret)
ok. changed. Now tokens are imported from main.py that has mapmyindia... token returning function

2023-02-11 11:35 UTC, GitCodeSM commented on locesh/server/api.py
> +token_type, access_token = startup_event(client_id, client_secret)
ok. removed

2023-02-11 11:35 UTC, GitCodeSM commented on locesh/server/api.py
>      print(distances)
commented the print

2023-02-11 11:37 UTC, GitCodeSM commented on locesh/distanceto/main.py
> +def mapmyindia_access_tokens(client_id: str, client_secret: str) -> tuple[str, str]:
changed

2023-02-11 11:38 UTC, GitCodeSM commented on locesh/distanceto/nearest.py
> +def get_closest_bus_stops(
commented out and changed in fetch_nearest... function as well

2023-02-11 11:39 UTC, GitCodeSM commented on locesh/distanceto/types.py
> +    BUS_STOP = "bus stop"
ok

2023-02-11 13:18 UTC, GitCodeSM commented on locesh/server/api.py
> +    token_type, access_token = mapmyindia_access_tokens(client_id, client_secret)
When I assign imported values to variables in this trigger event, it gives an error as variables aren't used anywhere. Also, I removed inputs and set the return type to none for the start event as you said in one of the reviews.

2023-02-11 19:05 UTC, GitCodeSM commented on locesh/distanceto/main.py
> +def mapmyindia_access_tokens(client_id: str, client_secret: str) -> tuple[str, str]:
but gave error:
distanceto\main.py:10:69: UP006 Use `tuple` instead of `Tuple` for type annotations

2023-02-11 19:06 UTC, GitCodeSM commented on locesh/distanceto/main.py
> +def mapmyindia_access_tokens(client_id: str, client_secret: str) -> tuple[str, str]:
fixing error reverted it back to tuple

2023-02-11 19:28 UTC, GitCodeSM commented on locesh/distanceto/nearest.py
> +    token_type, access_token, lat, lon, keywords
ok

2023-02-11 19:29 UTC, GitCodeSM commented on locesh/server/api.py
> +    token_type: str = token_type,
removed