added firebase configuration and dependencies
TechnocultureResearch/landlog pull request #5
Opened 2022-12-13 15:18 UTC by bhanu-priyaa

2022-12-20 16:32 UTC, sutyum commented on pages/lib/useFirebaseAuth.js
> +  }, []);
dependency list should not be empty and instead depend on `auth`

2022-12-20 16:56 UTC, sutyum requested changes

2022-12-20 16:56 UTC, sutyum commented on package.json
> +        "firebase-admin": "^11.4.0",
why is this needed?

2022-12-20 16:56 UTC, sutyum commented on pages/index.tsx
> +    //   const auth = initFirebase;
if this is not needed anymore, better to delete

2022-12-20 16:56 UTC, sutyum commented on pages/login/index.tsx
> +// import { signInWithEmailAndPassword } from 'firebase/auth';
remove if not needed anymore

2022-12-20 16:56 UTC, sutyum commented on pages/login/index.tsx
> +              {/* <div className="flex items-center justify-between">
remove

2022-12-20 16:56 UTC, sutyum commented on pages/login/index.tsx
> +                  <a
remove comments

2022-12-20 16:56 UTC, sutyum commented on pages/login/index.tsx
> +              {/* <div className="flex items-center justify-between">
remove comments

2023-01-23 18:02 UTC, sutyum requested changes
I have glanced at the PR, and some requested changes

2023-01-23 18:02 UTC, sutyum commented on next.config.js
> +module.exports = {
share a reference on why you have done it line this, earlier this was fine

2023-01-23 18:02 UTC, sutyum commented on pages/index.tsx
> +      // FETCH STUFF HERE
Is this needed?

2023-01-24 14:21 UTC, bhanu-priyaa commented on next.config.js
> +module.exports = {
https://nextjs.org/docs/api-reference/next.config.js/environment-variables
This is a reference to show the addition of enviroment variables in config file

2023-01-24 14:48 UTC, bhanu-priyaa commented on pages/api/entry/{id}.js
> +        else{
resolved issue with else block

2023-01-24 15:40 UTC, sutyum approved these changes

2023-01-24 15:40 UTC, merged